language: python
dist: Trusty
python:
  - "3.6"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
services:
  - postgresql
env:
  global:
    - SECRET = 'some-very-long-string-of-random-characters-CHANGE-TO-YOUR-LIKING'
before_script:
  - psql -c 'create database test_flask_api;' -U postgres
  - psql -c "ALTER USER "postgres" WITH PASSWORD 'newpassword';" -U postgres
after_success:
  coveralls
script:
- nosetests tests/
- nosetests  --with-coverage --cover-package=app
# ALTER USER "user_name" WITH PASSWORD 'new_password';